regras = {
    "Gripe": ["febre", "tosse", "dor_de_cabeca"],
    "Covid-19": ["febre", "tosse", "falta_de_ar", "perda_de_olfato"],
    "Enxaqueca": ["dor_de_cabeca", "nausea", "sensibilidade_a_luz"],
    "Alergia": ["espirros", "coceira", "coriza", "olhos_lacrimejantes"],
    "Dengue": ["febre", "dor_no_corpo", "manchas_na_pele", "dor_atras_dos_olhos"],
    "Amigdalite": ["dor_de_garganta", "febre", "dificuldade_para_engolir"],
    "Bronquite": ["tosse", "chiado_no_peito", "falta_de_ar"],
    "Sinusite": ["dor_de_cabeca", "congestao_nasal", "dor_facial", "secrecao_nasal"],
    "Pneumonia": ["febre", "tosse", "falta_de_ar", "dor_no_peito"],
    "Gastrite": ["dor_abdominal", "nausea", "azia", "inchaco"],
    "Insolação": ["febre_alta", "pele_seca_e_quente", "tontura", "confusao_mental"],
    "Tuberculose": ["tosse_persistente", "perda_de_peso", "sudorese_noturna", "febre"],
    "Diabetes_Tipo_2": ["sede_excessiva", "miccao_frequente", "fome_excessiva", "fadiga"],
    "Hipertensão": ["dor_de_cabeca", "tontura", "visao_borrada", "dor_no_peito"],
    "Ansiedade": ["palpitacoes", "suor_frio", "nervosismo", "falta_de_ar"],
    "Depressão": ["tristeza_persistente", "perda_de_interesse", "insonia", "fadiga"],
    "Artrite": ["dor_nas_articulacoes", "inchaco_nas_articulacoes", "rigidez_matinal", "febre_baixa"],
    "Caxumba": ["inchaco_no_pescoco", "febre", "dor_de_cabeca", "dor_ao_mastigar"],
    "Sarampo": ["febre", "manchas_vermelhas", "tosse", "coriza", "olhos_vermelhos"],
    "Rubeola": ["febre_baixa", "manchas_rosas", "dor_nas_articulacoes", "inchaco_dos_ganglios"],
    "Otite": ["dor_de_ouvido", "febre", "irritabilidade", "dificuldade_de_ouvir"],
    "Hepatite": ["ictericia", "dor_abdominal", "fadiga", "urina_escura"],
    "Conjuntivite": ["olho_vermelho", "coceira_nos_olhos", "sensibilidade_a_luz", "secrecao_nos_olhos"],
    "Gastroenterite": ["diarreia", "vomito", "dor_abdominal", "febre"],
    "Cistite": ["dor_ao_urinar", "miccao_frequente", "dor_no_baixo_ventre", "febre_baixa"]
}